name: Build PyTonk APK

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libssl-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv
        
    - name: Create buildozer.spec
      run: |
        echo "[app]" > buildozer.spec
        echo "title = PyTonk Game" >> buildozer.spec
        echo "package.name = pytonkgame" >> buildozer.spec
        echo "package.domain = com.pytonk.game" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "version = 1.0.0" >> buildozer.spec
        echo "requirements = python3, pygame==2.1.3, sdl2_ttf" >> buildozer.spec
        echo "orientation = landscape" >> buildozer.spec
        echo "fullscreen = 1" >> buildozer.spec
        echo "android.permissions = VIBRATE" >> buildozer.spec
        echo "android.arch = armeabi-v7a" >> buildozer.spec
        echo "p4a.branch = master" >> buildozer.spec
        echo "android.api = 33" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "android.sdk = 24" >> buildozer.spec
        
    - name: Build APK
      run: |
        buildozer -v android clean
        buildozer -v android debug
        cp bin/*.apk .
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: PyTonk-Game-APK
        path: |
          *.apk
